//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int idCliente { get; set; }
        public int tarjeta { get; set; }
        public string password { get; set; }
        public int dni { get; set; }
        public string nombre { get; set; }
    }
}
